name: movies_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/logo.png
    - assets/images/Movies Posters Group.png
    - assets/images/screen2.png
    - assets/images/The Godfather 2.png
    - assets/images/The Godfather 1.png
    - assets/images/xl_bad-boys-ride-or-die-movie-poster_591dcde0 2.png
    - assets/images/xl_bad-boys-ride-or-die-movie-poster_591dcde0 1.png
    - assets/images/xl_9419884_887ed6c7 2.png
    - assets/images/xl_9419884_887ed6c7 1.png
    - assets/images/1917_-_Sam_Mendes_-_Hollywood_War_Film_Classic_English_Movie_Poster_9ef86295-4756-4c71-bb4e-20745c5fbc1a 2.png
    - assets/images/1917_-_Sam_Mendes_-_Hollywood_War_Film_Classic_English_Movie_Poster_9ef86295-4756-4c71-bb4e-20745c5fbc1a 1.png

  uses-material-design: true

